# Generated by Django 3.1.6 on 2021-03-20 22:51

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='defaultuser.png', upload_to='users/image')),
                ('phone', models.IntegerField(default=0)),
                ('dob', models.DateField(default=datetime.datetime(2021, 3, 21, 4, 21, 53, 105686))),
                ('gender', models.CharField(default='', max_length=28)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
