# Generated by Django 3.1.6 on 2021-03-21 21:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_auto_20210321_0732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='dob',
            field=models.DateField(default=datetime.datetime(2021, 3, 22, 2, 32, 20, 826934)),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='image',
            field=models.ImageField(default='defaultuser.png', null=True, upload_to='users/image'),
        ),
    ]
