# Generated by Django 3.1.6 on 2021-03-22 04:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_auto_20210322_0926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='dob',
            field=models.DateField(default=datetime.datetime(2021, 3, 22, 10, 1, 23, 177879)),
        ),
    ]
