# Generated by Django 3.1.6 on 2021-03-22 04:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_auto_20210322_1001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='dob',
            field=models.DateField(default=datetime.datetime(2021, 3, 22, 10, 4, 8, 688213)),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='phone',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
