# Generated by Django 3.1.6 on 2021-03-21 21:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20210321_0732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 3, 22, 2, 32, 20, 784249)),
        ),
    ]
